services:
  qdrant_primary:
    image: qdrant/qdrant:latest
    container_name: qdrant_primary
    volumes:
      - ${QDRANT__STORAGE__VOLUME}/primary:/qdrant/storage
      - ./config/production.yaml:/qdrant/config/production.yaml
      - ./config/config.yaml:/qdrant/config/config.yaml
    ports:
      - "${QDRANT__PORT}:6333"
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "INFO"
    command: "./qdrant --config-path /qdrant/config/production.yaml --uri http://qdrant_primary:6335"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant_secondary_1:
    image: qdrant/qdrant:latest
    container_name: qdrant_secondary_1
    volumes:
      - ${QDRANT__STORAGE__VOLUME}/secondary_1:/qdrant/storage
      - ./config/production.yaml:/qdrant/config/production.yaml
      - ./config/config.yaml:/qdrant/config/config.yaml
    depends_on:
      - qdrant_primary
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "INFO"
    command: "./qdrant --config-path /qdrant/config/production.yaml --bootstrap http://qdrant_primary:6335 --uri http://qdrant_secondary_1:6335"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant_secondary_2:
    image: qdrant/qdrant:latest
    container_name: qdrant_secondary_2
    volumes:
      - ${QDRANT__STORAGE__VOLUME}/secondary_2:/qdrant/storage
      - ./config/production.yaml:/qdrant/config/production.yaml
      - ./config/config.yaml:/qdrant/config/config.yaml
    depends_on:
      - qdrant_primary
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "INFO"
    command: "./qdrant --config-path /qdrant/config/production.yaml --bootstrap http://qdrant_primary:6335 --uri http://qdrant_secondary_2:6335"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "${DOZZLE__PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Show only containers from this compose project (default project name is the folder name: qdrant-docker)
      - DOZZLE_FILTER=label=com.docker.compose.project=qdrant-docker
      - DOZZLE_TAILSIZE=3000
      - DOZZLE_LEVEL=info

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    pid: host
    ports:
      - "${GLANCES__PORT}:61208"
    environment:
      - GLANCES_OPT=--webserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
