services:
  qdrant-node1:
    image: qdrant/qdrant:latest
    container_name: qdrant-node1
    labels:
      - "com.qdrant.group=qdrant"
      - "com.qdrant.node=1"
    volumes:
      - ./data/node1:/qdrant/storage
    ports:
      - "6333:6333"   # HTTP
    environment:
      QDRANT__SERVICE__HTTP_PORT: "6333"
      QDRANT__SERVICE__GRPC_PORT: "6334"
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "INFO"
    command: "./qdrant --uri http://qdrant-node1:6335"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qdrant-net

  qdrant-node2:
    image: qdrant/qdrant:latest
    container_name: qdrant-node2
    labels:
      - "com.qdrant.group=qdrant"
      - "com.qdrant.node=2"
    volumes:
      - ./data/node2:/qdrant/storage
    depends_on:
      - qdrant-node1
    environment:
      QDRANT__SERVICE__HTTP_PORT: "6333"
      QDRANT__SERVICE__GRPC_PORT: "6334"
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "INFO"
    command: "./qdrant --bootstrap http://qdrant-node1:6335 --uri http://qdrant-node2:6335"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qdrant-net

  qdrant-node3:
    image: qdrant/qdrant:latest
    container_name: qdrant-node3
    labels:
      - "com.qdrant.group=qdrant"
      - "com.qdrant.node=3"
    volumes:
      - ./data/node3:/qdrant/storage
    depends_on:
      - qdrant-node1
    environment:
      QDRANT__SERVICE__HTTP_PORT: "6333"
      QDRANT__SERVICE__GRPC_PORT: "6334"
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "INFO"
    command: "./qdrant --bootstrap http://qdrant-node1:6335 --uri http://qdrant-node3:6335"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qdrant-net

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "${DOZZLE__PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Show only containers labeled as part of the Qdrant group
      - DOZZLE_FILTER=label=com.qdrant.group=qdrant
      - DOZZLE_TAILSIZE=3000
      - DOZZLE_LEVEL=info
    networks:
      - qdrant-net

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    pid: host
    ports:
      - "${GLANCES__PORT}:61208"
    environment:
      - GLANCES_OPT=--webserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    networks:
      - qdrant-net

networks:
  qdrant-net:
    driver: bridge
